name: etf-bot

on:
  workflow_dispatch:
  schedule:
  - cron: "3 1 * * *"   # 한국 10:05
  - cron: "7 5 * * *"   # 한국 14:05

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt

      - name: Run ETF Bot
        run: python main.py
        env:
          REST_API_KEY: ${{ secrets.REST_API_KEY }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}