name: etf-bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"   # 한국 10시
    - cron: "0 5 * * *"   # 한국 14시

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python main.py
  env:
    REST_API_KEY: ${{ secrets.REST_API_KEY }}
    CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}